### ISSUE TITLE
Alternative to presets file

### ISSUE THREAD

**Issue by dorchain** [vlcty/coredns-auto-ipv6-ptr#1]
Excuse me for this issue, I found no better way for a comment.

It is more of a story than anything, so here it goes

- I like the idea of autogenerated PTR-records for not fixed entries
- However, the format of the presets file is arbitrarily, I already have the data that would go in here in a zone file
- So, how to make autoipv6ptr take a zone file for presets?
- Not at all, use e.g. the existing file plugin for all the nitty-gritty of parsing etc.
- All that is left is a fallthrough option for the file plugin in case there no record exists in the zone file.
- So here is a first rough-cut and works-for-me patch:

```
diff --git a/plugin/file/file.go b/plugin/file/file.go
index 0834ddc4..3ed38da7 100644
--- a/plugin/file/file.go
+++ b/plugin/file/file.go
@@ -91,6 +91,10 @@ func (f File) ServeDNS(ctx context.Context, w dns.ResponseWriter, r *dns.Msg) (i
        m.Authoritative = true
        m.Answer, m.Ns, m.Extra = answer, ns, extra

+       if len(answer) == 0 {
+         log.Infof("No answer section -> fallthrough")
+               return plugin.NextOrFailure(f.Name(), f.Next, ctx, w, r)
+       }
        switch result {
        case Success:
        case NoData:

```
Allows for Corefile stanzas like
```
<reverse-network-zone>.ip6.arpa {
  file <reverse-network-zone>.ip6.arpa.zone
  autoipv6ptr {
      suffix example.org
  }
}

```

Alternative would be to copy the file plugin and insert the  synthesise function appropriately when there is a suffix option given

**Comment by vlcty** [comment]
Hi!

I'm very sorry. I somehow did not notice (or forgot) to look at this. You are right. It would be better to remove the presets file and load it from file (or maybe get it transferred from somewhere). When I initially created the plugin I was not very familiar with coredns and how its plugins should chain. I noticed while developing that having preset would be a nice feature and simply added it without further thinking.

I'm going to re-design this part. Thank you very much!
